# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
strategy:
  matrix:
    #Python27:
    #  python.version: '2.7'
    #Python35:
    #  python.version: '3.5'
    Python36:
      python.version: '3.6'
    #Python37:
    #  python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip wheel twine setuptools_scm
    pip install numpy
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'

- script: |
    python setup.py sdist bdist_wheel
  displayName: 'Build wheel'

# Python Twine Upload Authenticate
# Authentication for uploading Python distributions using twine.
# Please add '-r FeedName/EndpointName --config-file $(PYPIRC_PATH)
# to your twine upload command. For feeds present in this organization,
# use the feed name as the repository (-r). Otherwise, use the endpoint
# name defined in the service connection.
- task: TwineAuthenticate@0
  inputs:
    artifactFeeds:  # List of Azure Artifacts feeds to authenticate with twine.
    #externalFeeds: # Optional; List of service connections from external organizations

- script: 'twine -r {feedName/EndpointName} --config-file $(PYPIRC_PATH) --repository-url https://test.pypi.org/legacy/ dist/*'

